// Elite Credit AI - Sample audit data for "Carly Mendoza"
// Heavily realistic seed data: 12 accounts, 9 anomalies, deep edge cases

window.AUDIT_DATA = {
  user: {
    first_name: "Carly",
    last_name: "Mendoza",
    audit_date: "2026-04-28",
    ssn_last4: "4821",
  },

  routing: {
    flow: "A",
    flow_name_es: "Reparación",
    flow_name_en: "Repair",
    phase: 2,
    phase_name_es: "Disputas Específicas",
    phase_name_en: "Targeted Disputes",
    duration_weeks: "4–18",
    primary_goal_es: "Eliminar problemas críticos de tu reporte",
    primary_goal_en: "Remove critical problems from your report",
  },

  scores: {
    equifax:    { score: 615, grade: "FAIR", model: "VS 3.0", delta: -8 },
    experian:   { score: 622, grade: "FAIR", model: "VS 3.0", delta: -3 },
    transunion: { score: 608, grade: "POOR", model: "VS 3.0", delta: -12 },
  },

  factor_grades: [
    {
      factor_es: "Historial de pagos", factor_en: "Payment History",
      weight_fico: 35, weight_vs: 40, grade: "D",
      explanation_es: "Tienes 4 pagos atrasados reportados en los últimos 24 meses y un charge-off activo. Esto es lo que más afecta tu score.",
      explanation_en: "You have 4 late payments reported in the last 24 months and one active charge-off. This is what's hurting your score the most."
    },
    {
      factor_es: "Cantidad debida", factor_en: "Amounts Owed",
      weight_fico: 30, weight_vs: 20, grade: "F",
      explanation_es: "Estás usando 94% de tu crédito disponible. Lo ideal es estar bajo 30%. Una cuenta reporta saldo mayor que el límite.",
      explanation_en: "You're using 94% of your available credit. Ideal is under 30%. One account reports a balance higher than the limit."
    },
    {
      factor_es: "Antigüedad del crédito", factor_en: "Length of Credit",
      weight_fico: 15, weight_vs: 21, grade: "C",
      explanation_es: "Tu cuenta más antigua tiene 7 años. Está bien, pero podría ser mejor. No cierres cuentas viejas aunque no las uses.",
      explanation_en: "Your oldest account is 7 years old. It's okay, but could be better. Don't close old accounts even if you don't use them."
    },
    {
      factor_es: "Crédito nuevo", factor_en: "New Credit",
      weight_fico: 10, weight_vs: 5, grade: "B",
      explanation_es: "Solo 1 consulta dura en los últimos 12 meses. Bien hecho — no estás aplicando a crédito en exceso.",
      explanation_en: "Only 1 hard inquiry in the last 12 months. Well done — you're not over-applying for credit."
    },
    {
      factor_es: "Mezcla de crédito", factor_en: "Credit Mix",
      weight_fico: 10, weight_vs: 14, grade: "C",
      explanation_es: "Tienes tarjetas y un préstamo de auto. Una hipoteca o préstamo personal podría diversificar más, pero no es urgente.",
      explanation_en: "You have credit cards and an auto loan. A mortgage or personal loan could diversify further, but it's not urgent."
    }
  ],

  accounts: [
    {
      creditor: "Capital One Auto Finance",
      type_es: "Préstamo de auto", type_en: "Auto Loan",
      opened: "2022-03-01",
      balance: { eq: 5800, ex: 0, tu: 5800 },
      limit: null,
      status_per_bureau: { eq: "ChargeOff", ex: "Pays as Agreed", tu: "Closed" },
      friendly_status_es: "Necesita atención — los burós reportan diferente",
      friendly_status_en: "Needs attention — bureaus report differently",
      group: "attention",
      monthly: 0,
      utilization: null,
      last_activity: "2024-09-15",
      flags: ["cross_bureau_mismatch", "charge_off"],
    },
    {
      creditor: "Midland Credit Management",
      type_es: "Cobranza", type_en: "Collection",
      opened: "2024-08-10",
      balance: { eq: 1247, ex: 1247, tu: 1247 },
      limit: null,
      status_per_bureau: { eq: "Collection", ex: "Collection", tu: "Collection" },
      friendly_status_es: "En cobranza — exigir validación primero",
      friendly_status_en: "In collections — demand validation first",
      group: "collections",
      monthly: 0,
      original_creditor: "Synchrony Bank",
      utilization: null,
      last_activity: "2024-09-22",
      flags: ["unvalidated_debt", "junk_debt_buyer"],
    },
    {
      creditor: "LVNV Funding LLC",
      type_es: "Cobranza", type_en: "Collection",
      opened: "2023-11-05",
      balance: { eq: 892, ex: 892, tu: 0 },
      limit: null,
      status_per_bureau: { eq: "Collection", ex: "Collection", tu: "Removed" },
      friendly_status_es: "En cobranza — reportada solo en 2 burós",
      friendly_status_en: "In collections — only on 2 bureaus",
      group: "collections",
      monthly: 0,
      original_creditor: "Credit One Bank",
      utilization: null,
      last_activity: "2023-11-05",
      flags: ["cross_bureau_mismatch", "junk_debt_buyer", "stale_dofd"],
    },
    {
      creditor: "Capital One Bank USA",
      type_es: "Tarjeta de crédito", type_en: "Credit Card",
      opened: "2021-06-12",
      balance: { eq: 750, ex: 750, tu: 750 },
      limit: 500,
      status_per_bureau: { eq: "Pays as Agreed", ex: "Pays as Agreed", tu: "Pays as Agreed" },
      friendly_status_es: "Saldo mayor que el límite — error de reporte",
      friendly_status_en: "Balance over limit — reporting error",
      group: "attention",
      monthly: 35,
      utilization: 150,
      last_activity: "2026-04-10",
      flags: ["balance_over_limit"],
    },
    {
      creditor: "Discover Bank",
      type_es: "Tarjeta de crédito", type_en: "Credit Card",
      opened: "2019-02-20",
      balance: { eq: 2890, ex: 2890, tu: 2890 },
      limit: 3000,
      status_per_bureau: { eq: "Pays as Agreed", ex: "Pays as Agreed", tu: "Pays as Agreed" },
      friendly_status_es: "Al día — pero uso muy alto (96%)",
      friendly_status_en: "Current — but utilization very high (96%)",
      group: "attention",
      monthly: 95,
      utilization: 96,
      last_activity: "2026-04-22",
      flags: ["high_utilization"],
    },
    {
      creditor: "Chase Sapphire",
      type_es: "Tarjeta de crédito", type_en: "Credit Card",
      opened: "2020-08-04",
      balance: { eq: 340, ex: 340, tu: 340 },
      limit: 5000,
      status_per_bureau: { eq: "Pays as Agreed", ex: "Pays as Agreed", tu: "Pays as Agreed" },
      friendly_status_es: "Al día — uso saludable (7%)",
      friendly_status_en: "Current — healthy utilization (7%)",
      group: "good",
      monthly: 25,
      utilization: 7,
      last_activity: "2026-04-25",
      flags: [],
    },
    {
      creditor: "Wells Fargo Active Cash",
      type_es: "Tarjeta de crédito", type_en: "Credit Card",
      opened: "2023-01-15",
      balance: { eq: 0, ex: 0, tu: 0 },
      limit: 2500,
      status_per_bureau: { eq: "Pays as Agreed", ex: "Pays as Agreed", tu: "Pays as Agreed" },
      friendly_status_es: "Al día — sin saldo",
      friendly_status_en: "Current — no balance",
      group: "good",
      monthly: 0,
      utilization: 0,
      last_activity: "2026-03-30",
      flags: [],
    },
    {
      creditor: "Synchrony / Amazon Store",
      type_es: "Tarjeta de tienda", type_en: "Store Card",
      opened: "2018-11-22",
      balance: { eq: 0, ex: 0, tu: 0 },
      limit: 1200,
      status_per_bureau: { eq: "Closed", ex: "Closed", tu: "Closed" },
      friendly_status_es: "Cerrada — buen historial",
      friendly_status_en: "Closed — good history",
      group: "good",
      monthly: 0,
      utilization: 0,
      last_activity: "2024-12-01",
      flags: [],
    },
    {
      creditor: "Portfolio Recovery Associates",
      type_es: "Cobranza", type_en: "Collection",
      opened: "2022-04-18",
      balance: { eq: 2450, ex: 2450, tu: 2450 },
      limit: null,
      status_per_bureau: { eq: "Collection", ex: "Collection", tu: "Collection" },
      friendly_status_es: "Cobranza vieja — fecha de mora dudosa",
      friendly_status_en: "Old collection — DOFD looks suspect",
      group: "collections",
      monthly: 0,
      original_creditor: "Comenity Bank",
      utilization: null,
      last_activity: "2022-04-18",
      flags: ["stale_dofd", "junk_debt_buyer", "near_obsolescence"],
    },
    {
      creditor: "Navient Student Loan",
      type_es: "Préstamo estudiantil", type_en: "Student Loan",
      opened: "2017-09-01",
      balance: { eq: 18400, ex: 18400, tu: 18400 },
      limit: null,
      status_per_bureau: { eq: "Deferred", ex: "Deferred", tu: "Deferred" },
      friendly_status_es: "En aplazamiento — no afecta score por ahora",
      friendly_status_en: "In deferment — not affecting score for now",
      group: "good",
      monthly: 0,
      utilization: null,
      last_activity: "2026-04-01",
      flags: [],
    },
    {
      creditor: "Best Buy / Citibank",
      type_es: "Tarjeta de tienda", type_en: "Store Card",
      opened: "2020-12-04",
      balance: { eq: 480, ex: 0, tu: 480 },
      limit: 800,
      status_per_bureau: { eq: "Pays as Agreed", ex: "Closed", tu: "Pays as Agreed" },
      friendly_status_es: "Reportada cerrada en Experian, abierta en otros",
      friendly_status_en: "Reported closed on Experian, open on others",
      group: "attention",
      monthly: 25,
      utilization: 60,
      last_activity: "2026-04-15",
      flags: ["cross_bureau_mismatch"],
    },
    {
      creditor: "OneMain Financial",
      type_es: "Préstamo personal", type_en: "Personal Loan",
      opened: "2023-05-19",
      balance: { eq: 4200, ex: 4200, tu: 4200 },
      limit: null,
      status_per_bureau: { eq: "30 Days Late", ex: "Pays as Agreed", tu: "30 Days Late" },
      friendly_status_es: "Pago tarde reportado — pero pagaste a tiempo",
      friendly_status_en: "Late payment reported — but you paid on time",
      group: "attention",
      monthly: 178,
      utilization: null,
      last_activity: "2026-04-12",
      flags: ["disputed_late", "cross_bureau_mismatch"],
    },
  ],

  anomalies: [
    {
      id: "an1",
      severity: "HIGH",
      title_es: "Tu límite de crédito fue rebasado en el reporte",
      title_en: "Your reported balance is higher than your credit limit",
      explanation_es: "Capital One reportó un saldo de $750 cuando tu límite era $500. Los burós no deben aceptar cuentas reportadas así porque parece que estás en mora aunque no lo estés. Vamos a disputarlo.",
      explanation_en: "Capital One reported a $750 balance when your limit was $500. Bureaus shouldn't accept accounts reported this way because it makes you look delinquent when you're not. We'll dispute it.",
      affected: ["Capital One Bank USA"],
      action_es: "Disputar a los 3 burós bajo Metro2 accuracy + presentar queja CFPB simultánea",
      action_en: "Dispute with all 3 bureaus under Metro2 accuracy + file simultaneous CFPB complaint",
      citation: "FCRA §623(a)(2)",
    },
    {
      id: "an2",
      severity: "HIGH",
      title_es: "Cobranza sin validación de deuda",
      title_en: "Collection account with no debt validation",
      explanation_es: "Midland Credit dice que debes $1,247, pero nunca te enviaron prueba que la deuda es tuya ni que ellos tienen derecho de cobrarla. La ley dice que ellos deben validar antes de reportar.",
      explanation_en: "Midland Credit says you owe $1,247, but they never sent proof the debt is yours or that they have the right to collect. The law requires validation before reporting.",
      affected: ["Midland Credit Management"],
      action_es: "Carta de validación FDCPA — 30 días para responder o eliminar",
      action_en: "FDCPA validation letter — 30 days to respond or remove",
      citation: "FDCPA §1692g",
    },
    {
      id: "an3",
      severity: "HIGH",
      title_es: "Charge-off reportado diferente en cada buró",
      title_en: "Charge-off reported differently across bureaus",
      explanation_es: "Capital One Auto reporta como 'cargo cancelado' en Equifax, 'al día' en Experian, y 'cerrado' en TransUnion. La misma cuenta no puede tener tres estados. Por ley, los datos deben ser consistentes.",
      explanation_en: "Capital One Auto shows as 'charge-off' on Equifax, 'pays as agreed' on Experian, and 'closed' on TransUnion. The same account can't have three statuses. By law, data must be consistent.",
      affected: ["Capital One Auto Finance"],
      action_es: "Disputar inconsistencia cross-bureau + exigir revisión Metro2",
      action_en: "Dispute cross-bureau inconsistency + request Metro2 review",
      citation: "FCRA §611(a)",
    },
    {
      id: "an4",
      severity: "HIGH",
      title_es: "Pago tarde reportado que no fue tarde",
      title_en: "Late payment reported that wasn't actually late",
      explanation_es: "OneMain reporta un pago tarde de 30 días en Equifax y TransUnion, pero Experian lo muestra al día. Si pagaste a tiempo, los otros dos burós tienen un error.",
      explanation_en: "OneMain reports a 30-day late on Equifax and TransUnion, but Experian shows it current. If you paid on time, the other two bureaus have an error.",
      affected: ["OneMain Financial"],
      action_es: "Disputa con prueba de pago bancario + carta directa al furnisher",
      action_en: "Dispute with bank payment proof + direct furnisher letter",
      citation: "FCRA §623(b)",
    },
    {
      id: "an5",
      severity: "MEDIUM",
      title_es: "Cobranza vieja con fecha de mora dudosa",
      title_en: "Old collection with suspect delinquency date",
      explanation_es: "Portfolio Recovery reporta una fecha de mora original (DOFD) que se ve actualizada para mantener la cuenta en tu reporte más tiempo. Por ley, las cobranzas se quitan 7 años después de la mora original — no después.",
      explanation_en: "Portfolio Recovery reports an original delinquency date (DOFD) that looks re-aged to keep the account on your report longer. By law, collections fall off 7 years after the original delinquency — not later.",
      affected: ["Portfolio Recovery Associates"],
      action_es: "Disputar DOFD + solicitar registro Metro2 original",
      action_en: "Dispute DOFD + request original Metro2 record",
      citation: "FCRA §605(a)(4)",
    },
    {
      id: "an6",
      severity: "MEDIUM",
      title_es: "Cobranza reportada solo en 2 de 3 burós",
      title_en: "Collection reported on only 2 of 3 bureaus",
      explanation_es: "LVNV Funding reporta a Equifax y Experian, pero TransUnion ya la quitó. Eso es señal que TransUnion encontró algo malo. Podemos usar la misma evidencia con los otros dos.",
      explanation_en: "LVNV Funding reports to Equifax and Experian, but TransUnion already removed it. That signals TransUnion found something wrong. We can use the same evidence with the other two.",
      affected: ["LVNV Funding LLC"],
      action_es: "Disputa cross-bureau señalando la eliminación previa",
      action_en: "Cross-bureau dispute referencing the prior removal",
      citation: "FCRA §611(a)",
    },
    {
      id: "an7",
      severity: "MEDIUM",
      title_es: "Uso de crédito muy alto",
      title_en: "Credit utilization very high",
      explanation_es: "Estás usando 94% de tu crédito disponible. Bajar a 30% o menos puede subir tu score 30-60 puntos en 1-2 ciclos de reporte. No es disputa — es estrategia de pago.",
      explanation_en: "You're using 94% of your available credit. Getting to 30% or under can raise your score 30-60 points in 1-2 reporting cycles. Not a dispute — a payment strategy.",
      affected: ["Discover Bank", "Capital One Bank USA"],
      action_es: "Plan de pago dirigido + posible aumento de límite en Discover",
      action_en: "Targeted paydown plan + possible Discover limit increase",
      citation: "FICO scoring methodology",
    },
    {
      id: "an8",
      severity: "MEDIUM",
      title_es: "Cuenta reportada cerrada en un buró, abierta en otros",
      title_en: "Account reported closed on one bureau, open on others",
      explanation_es: "Best Buy / Citibank aparece cerrada en Experian pero abierta en Equifax y TransUnion. Hay que aclarar cuál es el estado real para que tu reporte sea consistente.",
      explanation_en: "Best Buy / Citibank shows closed on Experian but open on Equifax and TransUnion. We need to clarify the real status so your report is consistent.",
      affected: ["Best Buy / Citibank"],
      action_es: "Carta directa al furnisher pidiendo aclaración + dispute paralela",
      action_en: "Direct furnisher letter requesting clarification + parallel dispute",
      citation: "FCRA §623(a)(2)",
    },
    {
      id: "an9",
      severity: "LOW",
      title_es: "Variación menor de dirección entre burós",
      title_en: "Minor address variation between bureaus",
      explanation_es: "Tu dirección aparece como '1247 Maple St Apt 3' en Equifax y '1247 Maple St #3' en los otros. No afecta tu score pero conviene unificar para evitar mezclas con otra persona.",
      explanation_en: "Your address shows as '1247 Maple St Apt 3' on Equifax and '1247 Maple St #3' on the others. Doesn't affect your score but worth unifying to prevent mix-ups.",
      affected: ["Personal info"],
      action_es: "Solicitud rutinaria de actualización de PII",
      action_en: "Routine PII update request",
      citation: "FCRA §609",
    },
  ],

  action_plan: {
    expected_impact_es: "+80 a +150 puntos en 12-18 semanas",
    expected_impact_en: "+80 to +150 points in 12-18 weeks",
    total_disputable_items: 13,
    this_week: [
      {
        action_es: "Enviar carta de validación de deuda a Midland y LVNV",
        action_en: "Send debt validation letter to Midland and LVNV",
        reason_es: "FDCPA §1692g — antes de disputar a burós, ellos deben validar la deuda.",
        reason_en: "FDCPA §1692g — before disputing with bureaus, they must validate the debt.",
        effort: "30 min",
      },
      {
        action_es: "Pagar saldo de Capital One Bank a $400 (debajo del límite)",
        action_en: "Pay Capital One Bank balance down to $400 (below the limit)",
        reason_es: "Corregir el over-limit antes de disputar le quita argumento al banco.",
        reason_en: "Fixing the over-limit before disputing removes the bank's defense.",
        effort: "5 min",
      },
    ],
    weeks_2_3: [
      {
        action_es: "Disputar charge-off cross-bureau de Capital One Auto",
        action_en: "Dispute cross-bureau charge-off on Capital One Auto",
        reason_es: "La inconsistencia entre los 3 burós es violación FCRA §611(a).",
        reason_en: "The inconsistency across all 3 bureaus is an FCRA §611(a) violation.",
        effort: "1 h",
      },
      {
        action_es: "Disputar pago tarde de OneMain con prueba de pago",
        action_en: "Dispute OneMain late payment with payment proof",
        reason_es: "Experian lo muestra al día — los otros dos están equivocados.",
        reason_en: "Experian shows it current — the other two are wrong.",
        effort: "45 min",
      },
    ],
    weeks_4_8: [
      {
        action_es: "Si Midland/LVNV no validan en 30 días: dispute por eliminación",
        action_en: "If Midland/LVNV don't validate in 30 days: dispute for removal",
        reason_es: "FDCPA permite eliminación si no hay validación dentro del plazo.",
        reason_en: "FDCPA allows removal if no validation within the window.",
        effort: "1 h",
      },
      {
        action_es: "Disputar DOFD de Portfolio Recovery",
        action_en: "Dispute Portfolio Recovery DOFD",
        reason_es: "Posible re-aging — la cuenta debería estar cerca de eliminarse.",
        reason_en: "Possible re-aging — the account should be near falling off.",
        effort: "1 h",
      },
    ],
    weeks_8_18: [
      {
        action_es: "Bajar uso de Discover de 96% a debajo del 30%",
        action_en: "Bring Discover utilization from 96% to under 30%",
        reason_es: "Mayor impacto único de score por encima de cualquier disputa.",
        reason_en: "Single biggest score impact above any dispute.",
        effort: { es: "Continuo", en: "Ongoing" },
      },
      {
        action_es: "Solicitar aumento de límite en Discover y Wells Fargo",
        action_en: "Request credit limit increases on Discover and Wells Fargo",
        reason_es: "Más límite = menos uso reportado, sin gastar más.",
        reason_en: "More limit = lower reported utilization, without spending more.",
        effort: "15 min",
      },
    ],
  },

  account_context: {
    "Capital One Auto Finance": {
      letters_received_es: "Carta de Midland, Sep 2024",
      letters_received_en: "Letter from Midland, Sep 2024",
      calls_es: "3-4 por semana",
      calls_en: "3-4 per week",
      hardship_es: "Perdí trabajo en junio 2024",
      hardship_en: "Lost job June 2024",
      docs_es: "Tengo carta original de charge-off",
      docs_en: "I have original charge-off letter",
    },
    "Midland Credit Management": {
      letters_received_es: "Dunning de Midland, Sep 2024",
      letters_received_en: "Midland dunning letter, Sep 2024",
      calls_es: "Diario por 2 semanas",
      calls_en: "Daily for 2 weeks",
      hardship_es: "Misma situación de desempleo",
      hardship_en: "Same unemployment situation",
      docs_es: "Sin documentos",
      docs_en: "No documents",
    },
  },
};

// Translation helpers
window.t = function(es, en, lang) {
  return lang === "en" ? en : es;
};

window.getStatusLabel = function(status, lang) {
  const map = {
    "Pays as Agreed":   { es: "Al día", en: "Pays as Agreed" },
    "Closed":           { es: "Cerrada", en: "Closed" },
    "ChargeOff":        { es: "Cargo cancelado", en: "Charge-off" },
    "Collection":       { es: "Cobranza", en: "Collection" },
    "30 Days Late":     { es: "30 días tarde", en: "30 days late" },
    "Deferred":         { es: "Aplazada", en: "Deferred" },
    "Removed":          { es: "Eliminada", en: "Removed" },
  };
  const e = map[status];
  return e ? (lang === "en" ? e.en : e.es) : status;
};

window.getFlagLabel = function(flag, lang) {
  const map = {
    cross_bureau_mismatch: { es: "discrepancia entre burós",  en: "cross-bureau mismatch" },
    charge_off:            { es: "cargo cancelado",           en: "charge-off" },
    unvalidated_debt:      { es: "deuda sin validar",         en: "unvalidated debt" },
    junk_debt_buyer:       { es: "comprador de deuda chatarra", en: "junk debt buyer" },
    stale_dofd:            { es: "fecha de mora dudosa",      en: "stale DOFD" },
    near_obsolescence:     { es: "cerca de eliminarse",       en: "near obsolescence" },
    balance_over_limit:    { es: "saldo sobre el límite",     en: "balance over limit" },
    high_utilization:      { es: "uso alto",                  en: "high utilization" },
    disputed_late:         { es: "pago tarde disputado",      en: "disputed late" },
  };
  const e = map[flag];
  return e ? (lang === "en" ? e.en : e.es) : flag.replace(/_/g, " ");
};

window.getStatusColor = function(group) {
  return {
    good:        { border: "#1f3a2a", text: "#5fa87a", bg: "rgba(32,101,64,0.08)" },
    attention:   { border: "#3d3520", text: "#C4A052", bg: "rgba(196,160,82,0.08)" },
    collections: { border: "#3d1d22", text: "#d97082", bg: "rgba(176,54,66,0.08)" },
  }[group];
};

window.getGradeColor = function(grade) {
  // Unified palette — matches the score gauge band colors
  const map = {
    A: "#5FB97D", B: "#A8C957",
    C: "#E8C547",
    D: "#E08A3C", F: "#D24F66",
    EXCELLENT: "#5FB97D", VERY_GOOD: "#A8C957",
    GOOD: "#E8C547", FAIR: "#E08A3C", POOR: "#D24F66",
  };
  return map[grade] || "#E8C547";
};
